project:                
  type: website          
  output-dir: docs       
  
website:
  title: "Six Major Marathons"            #- hay q cambiarlo
  favicon: imagenes/star-World-Marathon-Majors.jpg 
  search:   
    location: navbar
    type: overlay   
    copy-button: true
  navbar:
    logo: "star-World-Marathon-Majors.jpg"           #---
    background: "#559CE4"    #- color de la navbar
    foreground: "#23445e"    #- color navigation elements, text and links that appear in the navbar.
    left: 
      - icon: house-door
        href: index.html
    right:
      - text: "Trabajo individual"   #---
        href: my_trabajo_BigData.qmd   
      - icon: github
        href: https://github.com/aanais02    #- pon tu usuario Github
      - icon: envelope
        url: "mailto:arossloy@alumni.uv.es"            #- pon tu e-mail
  page-footer:
    border: true
    background: "#23445e"
    foreground: "#FFFFFF" #--
    left: "© 2024 Anaïs Rosschaert Loyson"   #--
    center: "Hecho con [Quarto](https://quarto.org)"
    right:
      - icon: github
        href: https://github.com/aanais02     #- pon tu usuario Github
      - icon: envelope
        url: "mailto:arossloy@alumni.uv.es"            #- pon tu e-mail
    
format:
  html:
    theme: Morph           #- https://quarto.org/docs/output-formats/html-themes.html
    mainfont: Lato
    highlight-style: a11y   #-
    css: my_styles.css      #- si queréis añadir cosas
    page-layout: full
    toc: true
    toc-location: right
    toc-title: "Índice"
    code-copy: true
    code-overflow: wrap    
    code-fold: show
    code-line-numbers: true

# Enable CC licence appendix
#license: "CC BY"

lang: es  

# Default execute options
execute:
  echo: true
  message: false
  warning: false
  eval: true
  #fig-align: center
  #freeze: true  #- des-comentar cuando estéis tuneando el blog
                 #- https://quarto.org/docs/projects/code-execution.html#freeze
    

#- Default knitr options
knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    fig.asp:  7/9
    out.width: "95%"
    fig.align: "center"
    fig.show: "hold"
    R.options:
      options(scipen = 999) #- para quitar la notación científica  
